/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

import vm from 'vm';
import { join, parse } from 'path';
import { Logger } from './logger';
import { Config } from './configLocator';
import { readFileSync, promises as fs } from 'fs';
import { BundleSpec } from './computeBundles';
import { renameModule, wrapTextModule } from './bundleHelpers';
import { themeExists, getAllLanguages } from './magentoFS';

type Opts = {
    config: Config;
    bundleSpec: BundleSpec;
    requireConfig: RequireConfig;
    logger: Logger;
};
export async function createBundles(opts: Opts) {
    const { theme, staticFolderPath } = opts.config;
    const { groups, sharedGroups } = opts.bundleSpec;

    const exists = await themeExists(staticFolderPath, theme);
    if (!exists) {
        // TODO: Should check this _wayyy_ earlier in the app lifecycle
        // before ever fetching data from the store
        throw new Error(`Could not locate theme "${theme.name}"`);
    }

    const langs = await getAllLanguages(staticFolderPath, theme);
    opts.logger.log(
        `Found ${langs.length} languages for theme ${theme.name}: ${langs.join(
            ', ',
        )}`,
    );

    const firstLang = langs[0];
    const baseDir = join(
        staticFolderPath,
        'frontend',
        theme.vendor,
        theme.name,
        firstLang,
    );

    const resolve = createResolver(opts.requireConfig, baseDir);

    for (const [name, group] of groups) {
        const bundle = await generateBundleFile([...group.modules], resolve);
        await fs.writeFile(
            `/Users/andrewlevine/bundlegento/${name}.js`,
            bundle,
        );
    }

    for (const [name, group] of sharedGroups) {
        const bundle = await generateBundleFile([...group], resolve);
        await fs.writeFile(
            `/Users/andrewlevine/bundlegento/${name}.js`,
            'utf8',
            bundle,
        );
    }

    console.log('Wrote bundles');
}

const cache = new Map<string, string>();
async function generateBundleFile(
    modules: string[],
    resolver: ReturnType<typeof createResolver>,
) {
    const results = await Promise.all(
        modules.map(async id => {
            if (cache.has(id)) {
                return [id, cache.get(id) as string] as [string, string];
            }

            const mod = parseModuleID(id);
            const path = resolver(mod.id);
            let source = await fs.readFile(path, 'utf8');

            if (mod.isText) {
                source = wrapTextModule(mod.id, source);
            } else {
                source = renameModule(mod.id, source) || source;
            }

            cache.set(id, source);
            return [id, source] as [string, string];
        }),
    );

    return concatModules(new Map(results));
}

const requirejs = readFileSync(require.resolve('requirejs/require.js'), 'utf8');
// Piggy back on RequireJS's resolver so we don't have to duplicate that logic.
// Warning: Does not strip loaders i.e. "text!foo/bar"
function createResolver(requireConfig: RequireConfig, baseDir: string) {
    const sandbox = {};
    // RequireJS targeted at browsers, so it doesn't
    // have a CommonJS version, and just sets a global.
    // This is a quick hack to get what we need off that global
    vm.runInNewContext(requirejs, sandbox);
    // @ts-ignore
    sandbox.require.config({ ...requireConfig, baseUrl: '' });
    // @ts-ignore
    const nameToUrl = sandbox.require.s.contexts._.nameToUrl;

    return (id: string) => {
        const parts = parse(id);
        const rel: string = nameToUrl(join(parts.dir, parts.name), parts.ext);
        return join(baseDir, rel);
    };
}

function parseModuleID(id: string) {
    const parts = id.split('!');
    return {
        id: parts[parts.length - 1],
        isText: parts.includes('text'),
    };
}

function concatModules(modules: Map<string, string>) {
    let bundleSrc = `/* This file was generated by Bundlegento - ${Date()}  */\n\n`;
    for (const [id, source] of modules) {
        bundleSrc = `${bundleSrc}
/* ----- Start module: ${id} ----- */
${source}
/* ----- End module: ${id} ----- */\n`;
    }

    return bundleSrc;
}
